### ISSUE TITLE
Help: I don't get the steps

### ISSUE THREAD

**Issue by Echolon** [hpjansson/fornalder#12]
Hello,

unfortunately I am quite inexperienced with getting those repo files running. And I don't exactly understand the instructions.

- I cloned and build fornalder successfully
- I cloned the [repo](https://github.com/monal-im/Monal) of interest to my repository folder
-- /repositories/fornalder
-- /repositories/monal

How do I run these command exactly now?
```
$ target/debug/fornalder --meta projects/project-meta.json \
                         ingest db.sqlite repo-1.git repo-2.git ...
```

Sorry, I am a bit limited with my capabilities here... :(

**Comment by hpjansson** [comment]
Hi, try something like this:

```
$ cd repositories
$ fornalder/target/debug/fornalder ingest monal.db monal
$ fornalder/target/debug/fornalder plot monal.db monal.png
```

Then when you've got that working, try variants of the last command with different options described in `README.md`.

**Comment by Echolon** [comment]
Thank you very much! It worked! (just had to use 'Monal' not 'monal')
