### ISSUE TITLE
error: Gnuplort reported error

### ISSUE THREAD

**Issue by rvanlaar** [hpjansson/fornalder#16]
Hi, 

After reading your blog post I wanted to try this for myself. I get the following error on the scummvm repository: https://github.com/scummvm/scummvm.

`error: Gnuplot reported error`

Here is my full log. I'm using fornalder commit: 95f40e464b95

```fish
roland@MiX ~/wb8> git clone https://github.com/scummvm/scummvm
Cloning into 'scummvm'...
remote: Enumerating objects: 1012387, done.
remote: Counting objects: 100% (3359/3359), done.
remote: Compressing objects: 100% (1321/1321), done.
remote: Total 1012387 (delta 2183), reused 2985 (delta 2030), pack-reused 1009028
Receiving objects: 100% (1012387/1012387), 723.47 MiB | 3.33 MiB/s, done.
Resolving deltas: 100% (831372/831372), done.
Updating files: 100% (15528/15528), done.
roland@MiX ~/wb8> fornalder/target/debug/fornalder ingest db.sqlite scummvm
scummvm: 2021-08 (124143 commits)
roland@MiX ~/wb8 [1]> fornalder/target/debug/fornalder plot db.sqlite graph.png
error: Gnuplot reported error
roland@MiX ~/wb8 [1]> gnuplot -V
gnuplot 5.4 patchlevel 1
```

**Comment by hpjansson** [comment]
Hi, thanks for reporting this! I couldn't trigger the issue here, so I improved the error reporting on the master branch to hopefully get to the bottom of it.

Could you do a pull from master, build, trigger the issue and paste the (hopefully more detailed) error output?

**Comment by rvanlaar** [comment]
I was able to solve it thanks to the debug output. 
Long story short, I was using gnuplot from nix-packages. It had a problem with setting the right locale. Switching over to the gnuplot in my distro's repository fixed the problem.

For reference:
```
Gnuplot reported error: 
set decimalsign locale;
                ^
"/run/user/1000/.tmpU2IIKa" line 56: Could not find requested locale
```

Thanks again.

**Comment by hpjansson** [comment]
Glad you got it sorted. Kind of annoying though. Maybe Gnuplot should fall back to a hardcoded default if it can't load your locale.

The reason `set decimalsign locale` is in there is (as I recall) that it's the only way to make the subsequent `set format y "%'.0f"` work correctly, giving you thousands grouping separators (1,000, 1,000,000 etc).
